import createClient from "openapi-fetch";
import type { paths } from "./api-schema"; // generated by openapi-typescript

export const client = createClient<paths>({
    baseUrl: "http://localhost:3000/api",
    credentials: "include",
});
