import createClient from "openapi-fetch";

import type { paths } from "./api-schema";

// generated by openapi-typescript

export const API_URL = "http://localhost:3000/api";
export const client = createClient<paths>({
  baseUrl: API_URL,
  credentials: "include",
});
